---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Copy binary to remote host
  copy:
    src: ../../../go-chatgpt-telegram-bot
    dest: /home/deploy/go-chatgpt-telegram-bot
    owner: deploy
    group: deploy
    mode: '0755'

- name: Copy systemd service file
  template:
    src: go-chatgpt-telegram-bot.service.j2
    dest: /etc/systemd/system/go-chatgpt-telegram-bot.service

- name: Reload systemd to recognize new service
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start and enable the service
  ansible.builtin.systemd_service:
    name: go-chatgpt-telegram-bot
    enabled: true
    state: restarted
